language: node_js

node_js:
  - 8
  - 9
  - 10

sudo: false

git:
  depth: 1

cache:
  directories:
    - node_modules
    - ~/.npm

matrix:
  allow_failures:
    - node_js: 8

script:
  - npm run test

after_success:
  - npm run coverage
