sudo: false

language: node_js

node_js:
  - "11"
  - "10"
  - "8"
  - "7"

matrix:
  include:
    - name: "Node.js: nightly"
      node_js: "node"
      env:
        - NODEJS_ORG_MIRROR=https://nodejs.org/download/nightly
    - name: "Node.js: canary"
      node_js: "node"
      env:
        - NODEJS_ORG_MIRROR=https://nodejs.org/download/v8-canary

  allow_failures:
    - node_js: "node"
      env:
        - NODEJS_ORG_MIRROR=https://nodejs.org/download/nightly
    - node_js: "node"
      env:
        - NODEJS_ORG_MIRROR=https://nodejs.org/download/v8-canary

cache:
  directories:
    - node_modules
    - ~/.npm

git:
  depth: 5

script:
  - npm run test

after_success:
  - npm run coverage
