sudo: false

language: node_js

node_js:
  - 8.3
  - 9

matrix:
  include:
    - node_js: 10
      env: COVERAGE_TESTS=true
  allow_failures:
    - node_js: 8.3

cache:
  directories:
    - node_modules
    - ~/.npm

git:
  depth: 3

script:
  - npm run test

after_success:
  - env $COVERAGE_TESTS npm run coverage
